// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQKypvvuKsaXAaNd_A-vGb0vCzSZ7dkL4',
    appId: '1:546364339262:web:31c44d7c003770e1834d6f',
    messagingSenderId: '546364339262',
    projectId: 'badir-app-4b953',
    authDomain: 'badir-app-4b953.firebaseapp.com',
    databaseURL: 'https://badir-app-4b953-default-rtdb.firebaseio.com',
    storageBucket: 'badir-app-4b953.appspot.com',
    measurementId: 'G-JEXS0YXNET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApCGHc3EgtKhk8paEpAiP_K0KsM3i45cs',
    appId: '1:546364339262:android:3bc8965305b5924d834d6f',
    messagingSenderId: '546364339262',
    projectId: 'badir-app-4b953',
    databaseURL: 'https://badir-app-4b953-default-rtdb.firebaseio.com',
    storageBucket: 'badir-app-4b953.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp1IGtTrNWcyFU9alGehBhaH_N-JC9kj4',
    appId: '1:546364339262:ios:c2fc1172ce59fc16834d6f',
    messagingSenderId: '546364339262',
    projectId: 'badir-app-4b953',
    databaseURL: 'https://badir-app-4b953-default-rtdb.firebaseio.com',
    storageBucket: 'badir-app-4b953.appspot.com',
    iosBundleId: 'com.example.baderUserApp',
  );
}
